### PR TITLE
Fixes link to GH issue breaking on the gh-pages hosted version of the project

### PR DESCRIPTION
**Pull request by addyosmani**
Tried in Chrome + Chrome Canary: went to the footer on http://api.html5please.com and clicked on the link to the original issue. Rather than being taken to it this happened instead:

http://addyosmani.com/gyazo/2502d9.png

I'm guessing GH doesn't like the exclusion of `http://` on that one. The Get WebGL and link and link to Alexis' twitter account don't seem to have the same issue.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Two unrelated commits here. Why you should never pull request from master ;)

**Comment by addyosmani** [comment]
Lesson learned: never do this at 4am in the morning :) I'll resubmit a PR from branch later!

**Comment by nimbupani** [comment]
Seems to have been fixed already. thanks Addy!

**Comment by nimbupani** [comment]
If you add more items than that fit inside the input box, the items roll off the input box: http://cache.gyazo.com/a4eaad91e68efe0dd4d1ade6dcc7f14c.png Anyway we can scroll the view such that the end is always visible?

**Comment by addyosmani** [comment]
@nimbupani Just a UI idea, but how about extending the input box height (so it's effectively multi-line) once it crosses a certain number of characters? Might have to switch for a text-area or contentEditable to make that happen though.

**Pull request closed without merging**
