### PR TITLE
copy change

### PR DESCRIPTION
**Pull request by brucelawson**
changed "you've been in the awkward situation of telling some of your visitors that their browser isn't good enough" to ".. that their browser doesn't support those features" as it's less of a value judgement.

### CODE REVIEW

**Comment by nimbupani** [comment]
Thank you!

**Comment by brucelawson** [comment]
Yay for github. I could get the hang of this.

**Comment by paulirish** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by brucelawson** [comment]
fyi, prompted to change it based on this blogpost and my comment http://blog.adrianroselli.com/2012/03/return-of-viewed-in.html

**Pull request merged**
