### PR TITLE
Fixes #24 - adding real-time preview of JSON output

### LINKED ISSUE #24: show real output (of builder) next to the docs for output
> the "output" section might be better if it had an example of the json within it
> so you could see a real looking example of the current query

via @benschwarz

### PR DESCRIPTION
**Pull request by addyosmani**
Preview is hidden by default when the page loads. When a user selects a feature/set of features the preview displays with a simple pseudo-pretty-print. These changes have been applied to Divya's latest updates to only display JSON in the UI from a short while ago.

Screenshot: Screenshot

### CODE REVIEW

**Comment by addyosmani** [comment]
Sooo..I noticed that Divya's got inline previews for the widget/snippet code in place now with a message and link out to the API page if someone wants to see the output there. Looks like this:

test

In my opinion there's still an argument to be made for displaying the JSON output as a preview in the page. As a developer, it would quickly help me see what fields are being changed  in case I want to do something funky with them. Maybe there's still room for something like the above, even if just enabled via checkbox, @paulirish?

Totally cool with closing this if you don't need it, but happy to refactor and update my PR if you do.

**Comment by nimbupani** [comment]
Addy, I dunno, I prefer to make it dead simple to use on the first try and have docs elaborate how else it could be used. I think adding your demos/example page of other ways of styling/rendering the data would be massively useful in this regard rather than just plain JSON output here.

**Comment by paulirish** [comment]
I like it a lot. I was thinking of showing this output along the output reference.
I have an idea on how that could work and look decent.

**Comment by addyosmani** [comment]
Whatever you guys think is best :) If the output could be made to look better and could fit based on Paul's comments that would rock. If not, that's totes cool too.

**Comment by nimbupani** [comment]
I am closing this Addy, I made the url link to a readable version so that is available in a new window if necessary.

**Pull request closed without merging**
