### PR TITLE
Add parenthesis around the shorthand if/else

### PR DESCRIPTION
**Pull request by Keyamoon**
On line 46 of modernizr.html5please.js, parenthesis should be added around the if/else statement. Without them, <code>opts.options</code> which is intended to be the if condition, will first get concatenated with its previous strings.

### CODE REVIEW

**Comment by drublic** [comment]
Splitting with a space instead of `+` is already reported in #62.
The parenthesis look good to me. Can you reduce your PR for just the parenthesis?
Thank you for your heads up and work you put into it.

**Comment by Keyamoon** [comment]
No problem. I updated the pull request.

**Comment by drublic** [comment]
It's not yet in this PR or your repo :) Could you check this please? Thanks!

**Comment by Keyamoon** [comment]
Sorry I'm new to github; but I guess this is what you wanted? <a href="https://github.com/Keyamoon/html5please-api/commit/41a16845c17748c08a30f452795f0280d2a20a63">41a1684</a>

**Comment by drublic** [comment]
Thanks @Keyamoon for the changes. It was a bit hart to get the commit in it. I had to do some cherry picking as I didn't want to have all commits that are not related to the bug in it. I hope this is ok :). Your commit is [in here](https://github.com/h5bp/html5please-api/commit/1738c99a30e8809e66cc8ac65cb253cd1cf4fead).

Again, thank you for your work!

**Pull request closed without merging**
