### PR TITLE
Fixed sniffer regex to match internet explorer 11

### PR DESCRIPTION
**Pull request by micha149**
The guys from microsoft changed the user agent string for ie 11, to not match our used regular expressions. I added the „Trident“ part to fix this changes and match also to the new ua string pattern.

### CODE REVIEW

**Comment by eXaminator** [comment]
+1

**Comment by eXaminator** [comment]
I just fixed some backslash escaping

**Comment by eXaminator** [comment]
@tagawa or anyone involved, could we get some info if this will be merged at some point?

**Comment by tagawa** [comment]
It looks OK to me but I don't have IE to test it. If someone more qualified could test and resolve the merge conflicts that would be good.

**Comment by micha149** [comment]
Hi @tagawa. I've fixed the merge conflict. Simulating IE by changing your user-agent is no option? I thought about creating a test suite which passes all known user agents and test for the expected results. There are huge databases with user agent strings like [www.useragentstring.com](http://www.useragentstring.com/pages/useragentstring.php) which we can use for this.

**Comment by tagawa** [comment]
Finally got around to this. Thanks for the regex update and merge conflict fix.

**Pull request merged**
